services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./:/opt/app"
      - "./rootfs/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - "./:/opt/app"
      - "./rootfs/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"