services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./:/opt/app"
      - "./rootfs/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - "./:/opt/app"
      - "./rootfs/etc/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      - SERVER_NAME=localhost
      - SERVER_PORT=9999
      - SERVER_ROOT=/opt/app/public
      - SERVER_FPM_URL=fpm:9000

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: database
      POSTGRES_USER: database
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "database", "-U", "database"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
