services:
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "./:/opt/app"
      - "./rootfs/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - "./:/opt/app"
      - "./rootfs/etc/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      - SERVER_NAME=localhost
      - SERVER_PORT=9999
      - SERVER_ROOT=/opt/app/public
      - SERVER_FPM_URL=fpm:9000